// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: lancerLogin.proto
#ifndef GRPC_lancerLogin_2eproto__INCLUDED
#define GRPC_lancerLogin_2eproto__INCLUDED

#include "lancerLogin.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace lancer {

class LancerLoginServer final {
 public:
  static constexpr char const* service_full_name() {
    return "lancer.LancerLoginServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 注册接口
    virtual ::grpc::Status Register(::grpc::ClientContext* context, const ::lancer::RegisterReq& request, ::lancer::RegisterRsp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lancer::RegisterRsp>> AsyncRegister(::grpc::ClientContext* context, const ::lancer::RegisterReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lancer::RegisterRsp>>(AsyncRegisterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lancer::RegisterRsp>> PrepareAsyncRegister(::grpc::ClientContext* context, const ::lancer::RegisterReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lancer::RegisterRsp>>(PrepareAsyncRegisterRaw(context, request, cq));
    }
    // 登录接口
    virtual ::grpc::Status Login(::grpc::ClientContext* context, const ::lancer::LoginReq& request, ::lancer::LoginRsp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lancer::LoginRsp>> AsyncLogin(::grpc::ClientContext* context, const ::lancer::LoginReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lancer::LoginRsp>>(AsyncLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lancer::LoginRsp>> PrepareAsyncLogin(::grpc::ClientContext* context, const ::lancer::LoginReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lancer::LoginRsp>>(PrepareAsyncLoginRaw(context, request, cq));
    }
    // 通知push接口
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::lancer::NotifyReq, ::lancer::NotifyRsp>> Notify(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::lancer::NotifyReq, ::lancer::NotifyRsp>>(NotifyRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::lancer::NotifyReq, ::lancer::NotifyRsp>> AsyncNotify(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::lancer::NotifyReq, ::lancer::NotifyRsp>>(AsyncNotifyRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::lancer::NotifyReq, ::lancer::NotifyRsp>> PrepareAsyncNotify(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::lancer::NotifyReq, ::lancer::NotifyRsp>>(PrepareAsyncNotifyRaw(context, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::lancer::RegisterRsp>* AsyncRegisterRaw(::grpc::ClientContext* context, const ::lancer::RegisterReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::lancer::RegisterRsp>* PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::lancer::RegisterReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::lancer::LoginRsp>* AsyncLoginRaw(::grpc::ClientContext* context, const ::lancer::LoginReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::lancer::LoginRsp>* PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::lancer::LoginReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::lancer::NotifyReq, ::lancer::NotifyRsp>* NotifyRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::lancer::NotifyReq, ::lancer::NotifyRsp>* AsyncNotifyRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::lancer::NotifyReq, ::lancer::NotifyRsp>* PrepareAsyncNotifyRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Register(::grpc::ClientContext* context, const ::lancer::RegisterReq& request, ::lancer::RegisterRsp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lancer::RegisterRsp>> AsyncRegister(::grpc::ClientContext* context, const ::lancer::RegisterReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lancer::RegisterRsp>>(AsyncRegisterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lancer::RegisterRsp>> PrepareAsyncRegister(::grpc::ClientContext* context, const ::lancer::RegisterReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lancer::RegisterRsp>>(PrepareAsyncRegisterRaw(context, request, cq));
    }
    ::grpc::Status Login(::grpc::ClientContext* context, const ::lancer::LoginReq& request, ::lancer::LoginRsp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lancer::LoginRsp>> AsyncLogin(::grpc::ClientContext* context, const ::lancer::LoginReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lancer::LoginRsp>>(AsyncLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lancer::LoginRsp>> PrepareAsyncLogin(::grpc::ClientContext* context, const ::lancer::LoginReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lancer::LoginRsp>>(PrepareAsyncLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::lancer::NotifyReq, ::lancer::NotifyRsp>> Notify(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::lancer::NotifyReq, ::lancer::NotifyRsp>>(NotifyRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::lancer::NotifyReq, ::lancer::NotifyRsp>> AsyncNotify(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::lancer::NotifyReq, ::lancer::NotifyRsp>>(AsyncNotifyRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::lancer::NotifyReq, ::lancer::NotifyRsp>> PrepareAsyncNotify(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::lancer::NotifyReq, ::lancer::NotifyRsp>>(PrepareAsyncNotifyRaw(context, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::lancer::RegisterRsp>* AsyncRegisterRaw(::grpc::ClientContext* context, const ::lancer::RegisterReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::lancer::RegisterRsp>* PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::lancer::RegisterReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::lancer::LoginRsp>* AsyncLoginRaw(::grpc::ClientContext* context, const ::lancer::LoginReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::lancer::LoginRsp>* PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::lancer::LoginReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::lancer::NotifyReq, ::lancer::NotifyRsp>* NotifyRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::lancer::NotifyReq, ::lancer::NotifyRsp>* AsyncNotifyRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::lancer::NotifyReq, ::lancer::NotifyRsp>* PrepareAsyncNotifyRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Register_;
    const ::grpc::internal::RpcMethod rpcmethod_Login_;
    const ::grpc::internal::RpcMethod rpcmethod_Notify_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 注册接口
    virtual ::grpc::Status Register(::grpc::ServerContext* context, const ::lancer::RegisterReq* request, ::lancer::RegisterRsp* response);
    // 登录接口
    virtual ::grpc::Status Login(::grpc::ServerContext* context, const ::lancer::LoginReq* request, ::lancer::LoginRsp* response);
    // 通知push接口
    virtual ::grpc::Status Notify(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::lancer::NotifyRsp, ::lancer::NotifyReq>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Register() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Register(::grpc::ServerContext* context, const ::lancer::RegisterReq* request, ::lancer::RegisterRsp* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegister(::grpc::ServerContext* context, ::lancer::RegisterReq* request, ::grpc::ServerAsyncResponseWriter< ::lancer::RegisterRsp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Login() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* context, const ::lancer::LoginReq* request, ::lancer::LoginRsp* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLogin(::grpc::ServerContext* context, ::lancer::LoginReq* request, ::grpc::ServerAsyncResponseWriter< ::lancer::LoginRsp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Notify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Notify() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Notify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Notify(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::lancer::NotifyRsp, ::lancer::NotifyReq>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNotify(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::lancer::NotifyRsp, ::lancer::NotifyReq>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(2, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Register<WithAsyncMethod_Login<WithAsyncMethod_Notify<Service > > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Register() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Register(::grpc::ServerContext* context, const ::lancer::RegisterReq* request, ::lancer::RegisterRsp* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Login() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* context, const ::lancer::LoginReq* request, ::lancer::LoginRsp* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Notify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Notify() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Notify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Notify(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::lancer::NotifyRsp, ::lancer::NotifyReq>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Register : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Register() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::lancer::RegisterReq, ::lancer::RegisterRsp>(std::bind(&WithStreamedUnaryMethod_Register<BaseClass>::StreamedRegister, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Register() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Register(::grpc::ServerContext* context, const ::lancer::RegisterReq* request, ::lancer::RegisterRsp* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegister(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::lancer::RegisterReq,::lancer::RegisterRsp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Login() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::lancer::LoginReq, ::lancer::LoginRsp>(std::bind(&WithStreamedUnaryMethod_Login<BaseClass>::StreamedLogin, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Login(::grpc::ServerContext* context, const ::lancer::LoginReq* request, ::lancer::LoginRsp* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLogin(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::lancer::LoginReq,::lancer::LoginRsp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Register<WithStreamedUnaryMethod_Login<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Register<WithStreamedUnaryMethod_Login<Service > > StreamedService;
};

}  // namespace lancer


#endif  // GRPC_lancerLogin_2eproto__INCLUDED
